# This playbook detects changes in this configuration and adds/removes packages,apps,repos,rules as defined here

# sshd configuration
sshd_port: 22
# sshd_service: sshd
# sshd_package: openssh
# sshd_permit_empty_passwords: no
# sshd_permit_root_login: no
# sshd_password_authentication: no
# sshd_pubkey_authentication: yes
# sshd_x11_forwarding: no

# A list of packages to install
package_install: []
  # - zsh
  # - vim
  # - fzf

# A list of services to enable and run
services_enabled: []
  # - sshd

# A list of Flatpak apps to install
flatpak_apps: []
  # - com.brave.Browser
  # - com.spotify.Client@https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref

flatpak_repos:
  - name: flathub
    repo: https://flathub.org/repo/flathub.flatpakrepo

# A list of ufw rules to add
ufw_rules: []
  # - port: 443
  #   logging: low # can be omitted
  #   log: true # can be omitted
  #   rule: allow # can be omitted
  #   proto: tcp # can be omitted
  #   from_ip: any  # can be omitted
