---
- name: Installing openssh
  ansible.builtin.package:
    name: "{{ sshd_package | default('openssh') }}"

- name: Adjusting sshd config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    validate: sshd -Tf %s
    line: "{{ item.line }}"
    regex: "{{ item.regex }}"
  loop:
    - regex: ^#?Port
      line: Port {{ sshd_port | default(22) }}
    - regex: ^#?PasswordAuthentication
      line: PasswordAuthentication {{ sshd_password_authentication | default('no') }}
    - regex: ^#?PermitRootLogin
      line: PermitRootLogin {{ sshd_permit_root_login | default('no') }}
    - regex: ^#?PubkeyAuthentication
      line: PubkeyAuthentication {{ sshd_pubkey_authentication | default('yes') }}
    - regex: ^#?PermitEmptyPasswords
      line: PermitEmptyPasswords {{ sshd_permit_empty_passwords | default('no') }}
    - regex: ^#?X11Forwarding
      line: X11Forwarding {{ sshd_x11_forwarding | default('no') }}
  notify: Restart sshd
