---
- name: Installing flatpak
  ansible.builtin.package:
    name: flatpak

- name: Adding flatpak remote repositories
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ item.repo }}"
    name: "{{ item.name }}"
  loop: "{{ flatpak_repos }}"

- name: Removing flatpak repos
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ item.repo }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ansible_local.flatpak_repos | default(flatpak_repos) | difference(flatpak_repos) }}"

- name: Installing requested flatpak packages
  community.general.flatpak:
    name: "{{ parts[0] }}"
    from_url: "{{ parts[1] | default(omit) }}"
  vars:
    parts: "{{ item | split('@') }}"
  loop: "{{ flatpak_apps }}"

- name: Removing unspeficied flatpak packages
  community.general.flatpak:
    name: "{{ parts[0] }}"
    from_url: "{{ parts[1] | default(omit) }}"
    state: absent
  vars:
    parts: "{{ item | split('@') }}"
  loop: "{{ ansible_facts.ansible_local.flatpak_apps | default(flatpak_apps) | difference(flatpak_apps) }}"

- name: Creating facts.d directory
  ansible.builtin.file:
    state: directory
    path: /etc/ansible/facts.d
    owner: root
    mode: "0750"

- name: Saving current apps
  ansible.builtin.copy:
    content: "{{ flatpak_apps | to_json }}"
    dest: /etc/ansible/facts.d/flatpak_apps.fact
    owner: root
    mode: "0640"

- name: Saving current repos
  ansible.builtin.copy:
    content: "{{ flatpak_repos | to_json }}"
    dest: /etc/ansible/facts.d/flatpak_repos.fact
    owner: root
    mode: "0640"
