---
- name: Installing ufw
  ansible.builtin.package:
    name: ufw

- name: Allowing outgoing connections
  community.general.ufw:
    policy: allow
    direction: outgoing

- name: Denying incoming connections
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Allowing ssh port
  community.general.ufw:
    port: "{{ ansible_port }}"
    log: "{{ ufw_ssh_log | default(true) }}"
    rule: allow
  when: ansible_connection != 'local'

- name: Adding ports
  community.general.ufw:
    port: "{{ item.port }}"
    logging: "{{ item.logging | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    proto: "{{ item.proto | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
  loop: "{{ ufw_rules }}"

- name: Removing ports
  community.general.ufw:
    port: "{{ item.port }}"
    logging: "{{ item.logging | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    proto: "{{ item.proto | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    delete: true
  loop: "{{ ansible_facts.ansible_local.ufw_rules | default(ufw_rules) | difference(ufw_rules) }}"

- name: Creating facts.d directory
  ansible.builtin.file:
    state: directory
    path: /etc/ansible/facts.d
    mode: "0750"
    owner: root

- name: Saving rules state
  ansible.builtin.copy:
    content: "{{ ufw_rules | to_json }}"
    dest: /etc/ansible/facts.d/ufw_rules.fact
    mode: "0640"
    owner: root

- name: Enabling ufw
  community.general.ufw:
    state: enabled

- name: Enabling ufw in service manager
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: true
