---
- name: Enabling and running services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ services_enabled }}"

- name: Disabling and stopping services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ ansible_facts.local.services_enabled | default(services_enabled) | difference(services_enabled) }}"

- name: Creating facts.d directory
  ansible.builtin.file:
    state: directory
    path: /etc/ansible/facts.d
    owner: root
    mode: "0750"

- name: Saving current state
  ansible.builtin.copy:
    content: "{{ services_enabled | to_json }}"
    dest: /etc/ansible/facts.d/services_enabled.fact
    owner: root
    mode: "0640"
